---
services:
  perceived-temp-service:
    container_name: svc-frequency-handler
    image: svenschmidt1502/svc-frequency-handler:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
      - 'KAFKA_PRODUCER_TOPIC=${KAFKA_PRODUCER_TOPIC}'
      - 'KAFKA_CONSUMER_TOPIC=${KAFKA_CONSUMER_TOPIC}'
    deploy:
      replicas: 1